name: version
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v*'           # Push events to every tag starting with v

jobs:
  version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Deploy
        run: yarn lerna run deploy
        env:
          GH_TOKEN: ${{ github.token }}
