name: Test - Build - Version and Deploy

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          fetch-depth: 0

      - uses: c-hive/gha-yarn-cache@v2
      # Runs a single command using the runners shell

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test
        run: |
          yarn test:ci

      - name: Lint
        run: |
          yarn lint:ci

  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build:ci

      - name: Version
        run: yarn lerna version -y --conventional-commits --create-release github --loglevel verbose
        env:
          GH_TOKEN: ${{ github.token }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
